version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME:-dev}/frontend:${TAG:-latest}
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5002
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    image: ${DOCKER_USERNAME:-dev}/backend:${TAG:-latest}
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5002
    command: npm run dev